2019-12-31 10:11:47:     User(ID249403E8-3bUcGFAP) was authenticated successfully
2019-12-31 10:12:06: Unexpected exception
Traceback (most recent call last):
  File "G:\AI\MahjongAI-master\main.py", line 17, in connect_and_play
    return client.start_game()
  File "G:\AI\MahjongAI-master\client\tenhou_client.py", line 100, in start_game
    if not self._looking_for_a_game():
  File "G:\AI\MahjongAI-master\client\tenhou_client.py", line 220, in _looking_for_a_game
    msgs = self._get()
  File "G:\AI\MahjongAI-master\client\tenhou_client.py", line 683, in _get
    msgs = self.skt.recv(2048).decode('utf-8')
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2019-12-31 10:12:06: End the game...
2019-12-31 10:12:06:     Game was ended unexpected
2019-12-31 10:12:06: 
